export const books = [
  {
    title: "El Principito",
    author: "Antoine de Saint-Exupéry",
    gender: "Novela",
    language: "Español",
    price: "20000",
    availability: true,
    state: "Nuevo",
    editorial: "Editorial-Salamandra",
    pages: 100,
    description: "Un piloto perdido en el desierto encuentra a un pequeño príncipe que lo guía en un viaje lleno de sabiduría y descubrimiento.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675595/principito_ly0n3v.jpg'
  },
  {
    title: "Tokio Blues",
    author: "Haruki Murakami",
    gender: "Drama",
    language: "Inglés",
    price: "42000",
    availability: false,
    state: "Usado",
    editorial: "Tusquets-Editores",
    pages: 296,
    description: "Una historia de amor y pérdida que sigue a un estudiante universitario en Tokio mientras navega por la soledad y la angustia.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675596/tokio_wp3tsh.jpg'
  },
  {
    title: "Once Minutos",
    author: "Paulo Coelho",
    gender: "novela",
    language: "Inglés",
    price: "35900",
    availability: false,
    state: "Nuevo y usado",
    editorial: "Planeta",
    pages: 272,
    description: "Una joven brasileña viaja a Suiza en busca de una vida mejor, solo para verse atrapada en el mundo oscuro de la prostitución.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675581/once_hivfel.jpg'
  },
  {
    title: "La Metamorfosis",
    author: "Franz Kafka",
    gender: "Ficción",
    language: "Español/Inglés",
    price: "40000",
    availability: true,
    state: "Nuevo",
    editorial: "Editorial-Losada",
    pages: 160,
    description: "Gregor Samsa se despierta una mañana convertido en un insecto, enfrentando el rechazo de su familia y la transformación de su vida.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/metamorfosis_kw7qbs.jpg'
  },
  {
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes",
    gender: "Novela",
    language: "Español/Inglés",
    price: "50000",
    availability: true,
    state: "Nuevo",
    editorial: "Editorial-Cátedra",
    pages: 1024,
    description: "Las aventuras de un caballero soñador y su fiel escudero, Sancho Panza, que luchan contra molinos de viento y buscan justicia en un mundo de fantasía.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675596/quijote_horlp2.jpg'
  },
  {
    title: "Satanás",
    author: "Mario Mendoza",
    gender: "Novela",
    language: "Inglés",
    price: "15000",
    availability: false,
    state: "Nuevo",
    editorial: "Editorial-Planeta",
    pages: 376,
    description: "Una novela que explora los aspectos más oscuros de la mente humana a través de las perspectivas de un asesino en serie y un sacerdote atormentado.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675596/satanas_moq1rv.jpg'
  },
  {
    title: "La mecánica del corazón",
    author: "Mathias Malzieu",
    gender: "Cuento",
    language: "Español",
    price: "25000",
    availability: false,
    state: "Nuevo y usado",
    editorial: "Alfaguara",
    pages: 192,
    description: "Una fábula romántica y fantástica sobre un niño con un corazón de reloj, cuya vida se entrelaza con la de una niña enfermiza en la Escocia victoriana.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/mecanica_uoahfq.jpg'
  },
  {
    title: "La Ilíada",
    author: "Homero",
    gender: "Epopeya",
    language: "Español/Inglés",
    price: "29900",
    availability: true,
    state: "Usado",
    editorial: "Alianza-Editorial",
    pages: 576,
    description: "La célebre epopeya griega que narra los acontecimientos finales de la Guerra de Troya, con sus héroes, dioses y la ira de Aquiles.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/iliada_ao3m77.jpg'
  },
  {
    title: "El Perfume",
    author: "Patrick Süskind",
    gender: "Drama",
    language: "Español",
    price: "40000",
    availability: true,
    state: "Usado",
    editorial: "Seix-Barral",
    pages: 288,
    description: "La historia de Jean-Baptiste Grenouille, un hombre sin olor propio pero con un olfato excepcional, que busca crear el perfume perfecto a través de la explotación de otras personas.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675595/perfume_peiqo8.jpg'
  },
  {
    title: "Cien Años de Soledad",
    author: "Gabriel García Márquez",
    gender: "Novela",
    language: "Español",
    price: "70000",
    availability: false,
    state: "Nuevo",
    editorial: "Diana-Edit",
    pages: 471,
    description: "La saga de la familia Buendía a lo largo de varias generaciones en Macondo, una obra maestra de realismo mágico que explora temas de amor, soledad y destino.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/cien_q4hnkm.jpg'
  },
  {
    title: "La Odisea",
    author: "Homero",
    gender: "Epopeya",
    language: "Español",
    price: "20000",
    availability: false,
    state: "Nuevo",
    editorial: "Alianza-Editorial",
    pages: 384,
    description: "El viaje de Ulises de regreso a casa después de la Guerra de Troya, enfrentando peligros, desafíos y la ira de los dioses en su búsqueda de su amada Penélope.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675581/odisea_n6pfld.jpg'
  },
  {
    title: "Relato de un Náufrago",
    author: "Gabriel García Márquez",
    gender: "Drama",
    language: "Español",
    price: "40000",
    availability: false,
    state: "Usado",
    editorial: "Diana-Edit",
    pages: 144,
    description: "La crónica real del naufragio del marinero colombiano Luis Alejandro Velasco, su lucha por sobrevivir y su milagroso rescate.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/naufrago_jnsb4o.jpg'
  },
  {
    title: "El Señor de los Anillos",
    author: "J.R.R. Tolkien",
    gender: "Cuento",
    language: "Español",
    price: "80000",
    availability: true,
    state: "Nuevo",
    editorial: "Minotauro",
    pages: 1216,
    description: "Una epopeya de fantasía que sigue la búsqueda de un joven hobbit, Frodo Bolsón, para destruir un anillo que podría sumir a la Tierra Media en la oscuridad.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/anillos_bft5fx.jpg'
  },
  {
    title: "El Alquimista",
    author: "Paulo Coelho",
    gender: "Cuento",
    language: "Español",
    price: "20000",
    availability: true,
    state: "Usado",
    editorial: "Planeta",
    pages: 272,
    description: "La historia de Santiago, un pastor andaluz que emprende un viaje en busca de su 'leyenda personal', guiado por su corazón y las señales del universo.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/alquimista_ky3xcm.jpg'
  },
  {
    title: "Crepúsculo",
    author: "Stephenie Meyer",
    gender: "Fantasía",
    language: "Español",
    price: "40000",
    availability: true,
    state: "Usado",
    editorial: "Little,Brown-And-Company",
    pages: 544,
    description: "Una adolescente se enamora de un vampiro, desatando una serie de eventos que desafían la naturaleza y la realidad, en esta saga de romance paranormal.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/crepusculo_pzt88l.jpg'
  },
  {
    title: "El Diario de Ana Frank",
    author: "Anne Frank",
    gender: "Drama",
    language: "Español",
    price: "35000",
    availability: true,
    state: "Nuevo",
    editorial: "Fondo-De-Cultura-Económica",
    pages: 352,
    description: "El testimonio de una joven judía durante la Segunda Guerra Mundial, que narra su vida en un escondite en Ámsterdam y sus pensamientos más íntimos.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/anafrank_ceayat.jpg'
  },
  {
    title: "Los Cuatro Acuerdos",
    author: "Don Miguel Ruiz",
    gender: "Autoayuda",
    language: "Español",
    price: "20000",
    availability: true,
    state: "Usado",
    editorial: "Amber-Allen-Publishing",
    pages: 160,
    description: "Un libro de sabiduría tolteca que ofrece un camino hacia la libertad personal y la felicidad, basado en cuatro acuerdos simples pero poderosos.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/4ac_aiboic.jpg'
  },
  {
    title: "El Monje que Vendió su Ferrari",
    author: "Robin Sharma",
    gender: "Autoayuda",
    language: "Español",
    price: "25000",
    availability: true,
    state: "Nuevo",
    editorial: "Grijalbo",
    pages: 224,
    description: "Un abogado exitoso abandona su carrera y viaja a la India en busca de sabiduría y equilibrio, aprendiendo valiosas lecciones de un misterioso monje.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/monje_u30xxq.jpg'
  },
  {
    title: "El Túnel",
    author: "Ernesto Sabato",
    gender: "Ficción",
    language: "Español",
    price: "20000",
    availability: true,
    state: "Usado",
    editorial: "Seix-Barral",
    pages: 160,
    description: "Un hombre asesina a su esposa y relata su obsesión por una mujer que lo lleva por un camino de autodescubrimiento y desesperación en este clásico argentino.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675596/tunel_stuwg6.jpg'
  },
  {
    title: "Ángeles y Demonios",
    author: "Dan Brown",
    gender: "Drama",
    language: "Español",
    price: "35000",
    availability: true,
    state: "Nuevo",
    editorial: "Umbriel-Editores",
    pages: 576,
    description: "El profesor de simbología Robert Langdon se enfrenta a una conspiración en el Vaticano mientras busca detener un ataque que amenaza con desatar el caos.",
    image: 'https://res.cloudinary.com/erpersonalprojects/image/upload/v1718675580/angeles_Demonios_qdfpct.jpg'
  }  
]